### ISSUE TITLE
Error while running demo app on ios

### ISSUE THREAD

**Issue by kpachhai** [cyber-republic/react-native-elastos-wallet-core-demo#3]
```
** BUILD FAILED **



The following build commands failed:
	CompileC /Users/kpachhai/repos/github.com/cyber-republic/react-native-elastos-mainchain-demo/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/double-conversion.build/Objects-normal/x86_64/diy-fp.o /Users/kpachhai/repos/github.com/cyber-republic/react-native-elastos-mainchain-demo/node_modules/react-native/third-party/double-conversion-1.1.6/src/diy-fp.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/kpachhai/repos/github.com/cyber-republic/react-native-elastos-mainchain-demo/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/double-conversion.build/Objects-normal/x86_64/strtod.o /Users/kpachhai/repos/github.com/cyber-republic/react-native-elastos-mainchain-demo/node_modules/react-native/third-party/double-conversion-1.1.6/src/strtod.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/kpachhai/repos/github.com/cyber-republic/react-native-elastos-mainchain-demo/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/double-conversion.build/Objects-normal/x86_64/cached-powers.o /Users/kpachhai/repos/github.com/cyber-republic/react-native-elastos-mainchain-demo/node_modules/react-native/third-party/double-conversion-1.1.6/src/cached-powers.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/kpachhai/repos/github.com/cyber-republic/react-native-elastos-mainchain-demo/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/double-conversion.build/Objects-normal/x86_64/bignum.o /Users/kpachhai/repos/github.com/cyber-republic/react-native-elastos-mainchain-demo/node_modules/react-native/third-party/double-conversion-1.1.6/src/bignum.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/kpachhai/repos/github.com/cyber-republic/react-native-elastos-mainchain-demo/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/double-conversion.build/Objects-normal/x86_64/double-conversion.o /Users/kpachhai/repos/github.com/cyber-republic/react-native-elastos-mainchain-demo/node_modules/react-native/third-party/double-conversion-1.1.6/src/double-conversion.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/kpachhai/repos/github.com/cyber-republic/react-native-elastos-mainchain-demo/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/double-conversion.build/Objects-normal/x86_64/fast-dtoa.o /Users/kpachhai/repos/github.com/cyber-republic/react-native-elastos-mainchain-demo/node_modules/react-native/third-party/double-conversion-1.1.6/src/fast-dtoa.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/kpachhai/repos/github.com/cyber-republic/react-native-elastos-mainchain-demo/ios/build/Build/Intermediates.noindex/React.build/Debug-iphonesimulator/double-conversion.build/Objects-normal/x86_64/fixed-dtoa.o /Users/kpachhai/repos/github.com/cyber-republic/react-native-elastos-mainchain-demo/node_modules/react-native/third-party/double-conversion-1.1.6/src/fixed-dtoa.cc normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(7 failures)

Installing build/Build/Products/Debug-iphonesimulator/RNMainchainDemo.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/RNMainchainDemo.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist


Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/RNMainchainDemo.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:618:11)
    at Object.execFileSync (child_process.js:636:13)
    at Promise.then (/Users/kpachhai/repos/github.com/cyber-republic/react-native-elastos-mainchain-demo/node_modules/react-native/local-cli/runIOS/runIOS.js:208:5)
```

**Comment by kpachhai** [comment]
doing ```react-native upgrade``` fixed the issue but i encountered another error.
<img width="351" alt="screen shot 2018-11-09 at 16 02 10" src="https://user-images.githubusercontent.com/2739378/48288042-d5bc7780-e438-11e8-94ae-0ea12449bb65.png">

**Comment by ademcan** [comment]
The updated instructions should fix this issue.

**Comment by kpachhai** [comment]
Thanks
